version: '3.3'
services:
  server:
    build: .
    environment:
      DB_HOST: "db"
      DB_HOST: "dbAuth"
    ports:
      - 3000:3000
      - 8000:8000
      - 9000:9000
    depends_on:
      - db
      - dbAuth
    links:
      - db
      - dbAuth
    
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: blogdatabase
    ports:
      - 27017:27017

  dbAuth: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: userdatabase
    ports:
      - 20000:20000